apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: quarkus-cafe-app-cluster3
  namespace: quarkus-cafe-demo
  labels:
    deployment: quarkus-cafe-app
  annotations:
    apps.open-cluster-management.io/github-branch: v2.4.0
    apps.open-cluster-management.io/github-path: clusters/overlays/cluster3
spec:
  channel: quarkus-cafe-demo/quarkus-cafe-demo-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: cluster3
